### ISSUE TITLE
Response bit

### ISSUE THREAD

**Issue by stbluesrul** [avahi/avahi#131]
Does anyone know how to set the response bit?

I need Avahi to reply to both QU and QM questions.

**Comment by evverx** [comment]
> Does anyone know how to set the response bit?

It depends on what is used to send queries. `dns-sd` provides https://developer.apple.com/documentation/dnssd/1823436-anonymous/kdnsserviceflagsunicastresponse but it's a no-op nowadays as far as I can tell and the first query is always a "QU" query there.

`avahi` doesn't send "QU" queries. It's possible to build a packet with the "QU" bit set using `avahi_dns_packet_append_key` though.

> I need Avahi to reply to both QU and QM questions.

avahi can reply to those queries as long as the bit is set or unset.

"QU" queries are kind of tracked in https://github.com/avahi/avahi/issues/546 so I'll go ahead and close this issue.
