### ISSUE TITLE
translation for friulian

### ISSUE THREAD

**Issue by tmtfx** [avahi/avahi#170]
I've just translated avahi for friulian language (I'm the friulian translation team coordinator in gnome, fedora, TP and more...)

If you intend adding it, also LINGUAS file should be modified adding "fur" to the list
[avahi.po.master.fur.po.gz](https://github.com/lathiat/avahi/files/1773952/avahi.po.master.fur.po.gz)

The file attached is a gzipped po file, it must be decompressed before putting it into the "po" directory
Regards,
Fabio Tomat

**Comment by tmtfx** [comment]
Obviously, after decompressing it should also be renamed to fur.po

**Comment by evverx** [comment]
Thanks! Could you open a PR?

(Generally I recently pushed a couple changes suggested back in 2018 attributed to their authors but they were bug fixes. I think in this particular case it would be better if it was done by a native Friulian speaker just to take a final look to see whether it's up to date).

**Comment by evverx** [comment]
avahi should be hopefully integrated into the Fedora Weblate instance soon: https://github.com/avahi/avahi/issues/603. It's tracked in https://pagure.io/fedora-l10n/tickets/issue/40.

**Comment by evverx** [comment]
Now that avahi is integrated into Weblate and receives updates like https://github.com/avahi/avahi/pull/632 could you upload the changes via https://translate.fedoraproject.org/engage/avahi?

I'll go ahead and close this issue here because the translations are tracked and handled via Weblate now.

**Comment by tmtfx** [comment]
Oh boy, I missed to answer the notification, sorry! I'm starting over the translation on weblate right now. Thank you!

**Comment by evverx** [comment]
Weblate already opened https://github.com/avahi/avahi/pull/634. I'll keep it open until it pulls all the changes from Weblate. Thank you!
