### ISSUE TITLE
is avahi able to MAC to IP binding

### ISSUE THREAD

**Issue by mayurpatelgec** [avahi/avahi#188]
Hi.. i am newbie to avahi and I want to **map all devices having MAC to specific IP**.. is ithis possible via avahi / avahi-autoipd? there will be one file created from config software and avahi will be able to read it..

Something like this....
```
# MAC address to IP mapping


host copeedddl {
hardware ethernet 00:0d:54:a8:90:85;
fixed-address 188.37.65.22;
}

host akroasdku {
hardware ethernet 00:08:74:46:89:db;
fixed-address 188.37.65.30;
}

host NP15F3B33EC {
hardware ethernet 00:01:e6:5f:3b:ec;
fixed-address 188.37.65.216;
}

host lpt106aa {
hardware ethernet 00:06:5b:02:bd:67;
fixed-address 188.37.65.8;
}
```

**Comment by mayurpatelgec** [comment]
thank you @lathiat for the speedy response.  is there any other possibility that I get the same IP every time with avahi?

**Comment by lathiat** [comment]
There is not. The only functionality avahi implements IP configuration is the zeroconf IP spec (with avahi-autoipd) which is specifically designed to always pick a random address. 

What most people do instead is use the random IP allocation (or just allocation from the normal DHCP sever) and then use libnss-mdns to look the machine up by the .local hostname, eg ping my-hostname.local or http://my-hostname.local etc
