### ISSUE TITLE
Feature Request: Multi-Instance capability

### ISSUE THREAD

**Issue by devZer0** [avahi/avahi#213]
I needed to setup a second because i hit the "Record too large, cannot send" limit when announcing a bunch of timemachine smb shares. see https://lists.freedesktop.org/archives/avahi/2011-September/002082.html

i did a workaround by splitting the announces and let the new records be announced by another avahi instance on a different system.

but i dislike running another extra system for that to workaround this issue, why seems to be missing is to have avahi run as a second instance on a different network interface for the same purpose. think there are paths hardcoded and i cannot change them without modifying sourcode.

i think multi instance capability should not be too hard to do, as you can tell avahi which interface to attach to

**Comment by paul-hammant** [comment]
You were trying to get one Samba host machine to serve up two timemachines? Say, you and spouse?

I am trying to do the same.  I tried to duplicate a `<service/>` section in `/etc/avahi/services/samba.service` but the Mac failed to see the availability of either. Take out the second `<service/>` section and it works again afer `systemctl restart avahi-daemon`. Too bad.  A docker way would would, but I wish docker had an easy `--assign-container-ip-from-host-dhcp`. Maybe Proxmox with LXC containers is the way as it assigns IP addresses by default.

**Comment by evverx** [comment]
> i did a workaround by splitting the announces and let the new records be announced by another avahi instance on a different system

It should be possible for one instance of avahi to publish services with the same names on different interfaces using the D-Bus API by passing the "interface" argument. There was an attempt to bring interfaces to avahi static service files in https://github.com/avahi/avahi/pull/33 but it hasn't been merged yet.

> to have avahi run as a second instance on a different network interface for the same purpose.

This feature requests is tracked at https://github.com/avahi/avahi/issues/67.

**Comment by paul-hammant** [comment]
I got it broadcasting two late yesterday:

```
<service>
    <type>_adisk._tcp</type>
    <txt-record>dk0=adVN=timemachine_for_me,adVF=0x82</txt-record>
    <txt-record>dk1=adVN=timemachine_for_spouse,adVF=0x82</txt-record>
    <txt-record>sys=waMa=0,adVF=0x100</txt-record>
  </service>
```
