### ISSUE TITLE
hostnames longer than 57 chars fail to resolve

### ISSUE THREAD

**Issue by jvfranklin** [avahi/avahi#273]
I’m seeing a problem with Avahi failing to resolve hostnames that are longer than 57 characters.

I’m running on Linux, with Avahi 0.7.  If I set the hostname to something like abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz01234567890, and try to ping it with “ping abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz01234567890.local”, I get this:

/# ping abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz01234567890.local
ping: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz01234567890.local: Temporary failure in name resolution

If I run it with strace, it shows it's getting rejecting as invalid host name:

connect(5, {sa_family=AF_UNIX, sun_path="/var/run/avahi-daemon/socket"}, 110) = 0
fcntl64(5, F_GETFL)                     = 0x2 (flags O_RDWR)
fstat64(5, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0 write(5, "RESOLVE-HOSTNAME-IPV4 abcdefghij"..., 92) = 92 read(5, "-3 Invalid host name\n", 4096) = 21

I've tracked down the initial failure to avahi-daemon/simple-protocol.c in the handle_line function.  The sscanf call only reads 64 characters total for "hostname.local", which obviously will lose the last part of the string if hostname is too long.  Increasing the buffer size still doesn't get things working, but at least it gets past the "invalid host name" problem.  Maybe someone more familiar with the code can figure out where else it's failing?

Avahi-resolve has no issues with the same hostname.  Looks like it's specific to the nss-mdns lookups.

**Comment by pusateri** [comment]
A DNS name is made up of multiple strings separated by a period like "example.com" or "foo.bar.com". Each string portion is called a label and the maximum label length is 63 bytes. The total DNS name can be longer but each label is limited by the proceeding single byte count with the first two bits as zero (00111111) which gives you the 63 byte limit. This limit isn't part of Avahi but a restriction of the DNS packet format.

**Comment by jvfranklin** [comment]
The label length is understood.  The problem I'm having is that the DNS name I want Avahi to resolve is limited to 63 bytes.  It's not handling a longer name than that.  Should Avahi be able to resolve the name abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz01234567890.local?  That's a legal hostname in Linux.  The label lengths are fine: both within 63 chars.  The overall length exceeds 63 chars.

Avahi-resolve handles it, but lookups through nss-mdns calls do not.

**Comment by lathiat** [comment]
Yeah this sounds like a bug I’ll look into it
