### ISSUE TITLE
Avahi browse yields no result with reflect-filters

### ISSUE THREAD

**Issue by thburghout** [avahi/avahi#297]
Hi,

I was playing around with the new reflect-filters option in avahi 0.8. However, I found that `avahi-browse -a` yields no results when I enabled the reflector (`enable-reflector=yes`) and set an arbitrary filter (`reflect-filters=foo`).

The documentation on `reflect-filters` suggests that the filter only applies on whether or not a packet is reflected. The actual behavior seems to be filtering the packets altogether.

Am I missing something here? Maybe @dkerr64 would be able to comment on this issue.

Thanks!

**Comment by dkerr64** [comment]
@thburghout I will take a look at this when I have a chance.

**Comment by transpetaflops** [comment]
I stumbled upon this problem today while trying to make two subnets exchange avahi information with each other.

If I set enable-reflector to yes, local services disappear from the output of avahi-browse -at. Resetting it to no makes local services show up in the output again. Other services on the LAN are always visible regardless of that setting. While reflector is enabled, LAN clients can not resolve the router's .local address so it doesn't seem to be a simple display error.

The log output from avahi-daemon is identical regardless of the reflector setting, with the exception of the "Local service cookie". Avahi is new territory to me so I need some pointers to what else I can compare between the two configurations. Most likely there's something I did wrong and I'd appreciate some suggestions.

System is FreeBSD 13.0-RELEASE-p5 and avahi version is 0.8.

**Comment by evverx** [comment]
It kind of works as expected:
> The filter also blocks local programs from seeing advertised programs so it is recommend to only enable it on a dedicated bonjour reflector server

but it isn't documented anywhere unfortunately. It would probably make sense to document this feature better. It seems the documentation could also help to address https://github.com/lathiat/avahi/issues/438.

**Comment by evverx** [comment]
It is a regression introduced in https://github.com/avahi/avahi/pull/263. It's tracked in https://github.com/avahi/avahi/issues/611.
