### ISSUE TITLE
Resolving Service name conflicts

### ISSUE THREAD

**Issue by asmithakarun** [avahi/avahi#303]
When I was trying to do 'avahi-browse', I was able to see service name conflicts (since the service with the same name would be published by various clients in the network and I could see that the service was renamed as <servicename>#100, after trying for 99 times).

To resolve this, the idea is to append the hostname of the client with the service name (whenever the service is being published), given that the hostname will always be unique in my case.

So, the service file would look like: (example.service)
<service-group>
       <name>example-hostname</name>
       <service>
               <type>...</type>
               <port>...</port>
       </service>
</service-group>

Will the above be a valid solution or should there be a patch for avahi to resolve the service name conflicts?

**Comment by asmithakarun** [comment]
example.service:

```
<service-group>
       <name>example-hostname</name>
       <service>
               <type>...</type>
               <port>...</port>
       </service>
</service-group>
```

**Comment by A-Fromell-ITxPT** [comment]
Try to use:
`<service-group>
       <name replace-wildcards="yes">%h</name>
       <service>
               <type>...</type>
               <port>...</port>
       </service>
</service-group>`

Best regards,
Anders

**Comment by evverx** [comment]
`%h` should do the trick. Closing.
