### ISSUE TITLE
hostname conflict with dynamic ipv6

### ISSUE THREAD

**Issue by dwery** [avahi/avahi#340]
Every time there is a dynamic ipv6 change, avahi detects an hostname conflict and increments the hostname:
May 15 02:01:57 foobar dhcpcd[1367]: eth0: Router Advertisement from fe80::8c4:......
May 15 02:01:57 foobar avahi-daemon[1539]: Registering new address record for .....
May 15 02:01:57 foobar avahi-daemon[1539]: Host name conflict, retrying with foobar-20

**Comment by evverx** [comment]
Looks like it's a duplicate of https://github.com/avahi/avahi/issues/117.
