### ISSUE TITLE
Only 1 VLAN (of 3) interface rejoins multicast group when link drops and is reestablished

### ISSUE THREAD

**Issue by c6rbon** [avahi/avahi#417]
# Problem

When a physical link drops and reconnects on pfsense, avahi is only re-joining 1 VLAN interface to the multicast group out of the 3 that it is configured to reflect between. My current work-around is to manually restart avahi when this happens.

# Background 
 
avahi-app-0.8 and nss_mdns-0.14.1.20200624 packages running under pfsense 2.6.0.

The physical interface igb1 is plugged into a unifi US-8-150W running 6.3.13 firmware.

igb1 has a set of 5 VLANs. avahi is configured to listen and send on 3 of them (tags 30, 40 & 50), and is used for reflection between the VLANs. It is currently configured for both IPv4 and IPv6.

Caveat: I'm not an expert in any of these tools.

# Startup (works fine)

When avahi starts, it correctly discovers the three relevant interfaces (for each of IPv4 and IPv6), and joins each to the multicast group:

```
Dec  3 15:06:00 pfSense avahi-daemon[30268]: Joining mDNS multicast group on interface igb1.40.IPv6 with address XX::XX.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: New relevant interface igb1.40.IPv6 for mDNS.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: Joining mDNS multicast group on interface igb1.40.IPv4 with address X.X.X.X.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: New relevant interface igb1.40.IPv4 for mDNS.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: Joining mDNS multicast group on interface igb1.30.IPv6 with address XX::XX.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: New relevant interface igb1.30.IPv6 for mDNS.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: Joining mDNS multicast group on interface igb1.30.IPv4 with address X.X.X.X.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: New relevant interface igb1.30.IPv4 for mDNS.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: Joining mDNS multicast group on interface igb1.50.IPv6 with address XX::XX.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: New relevant interface igb1.50.IPv6 for mDNS.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: Joining mDNS multicast group on interface igb1.50.IPv4 with address X.X.X.X.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: New relevant interface igb1.50.IPv4 for mDNS.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: Network interface enumeration completed.
Dec  3 15:06:00 pfSense avahi-daemon[30268]: Server startup complete. Host name is pfSense.local. Local service cookie is CCCCCCCC.
```

You can see the end state of multicast membership includes all three of these VLAN interfaces; the 3 we care about :

```
ifmcstat -f inet -v #edited

igb1:
	inet X.X.X.X
	igmpv3 rv 2 qi 125 qri 10 uri 3
		group 224.0.0.1 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
igb1.50:
	inet X.X.X.X
	igmpv3 rv 2 qi 125 qri 10 uri 3
		group 224.0.0.251 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
		group 224.0.0.1 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
igb1.30:
	inet X.X.X.X
	igmpv3 rv 2 qi 125 qri 10 uri 3
		group 224.0.0.251 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
		group 224.0.0.1 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
igb1.40:
	inet X.X.X.X
	igmpv3 rv 2 qi 125 qri 10 uri 3
		group 224.0.0.251 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
		group 224.0.0.1 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
igb1.100:
	inet X.X.X.X
	igmpv3 rv 2 qi 125 qri 10 uri 3
		group 224.0.0.1 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
igb1.90:
	inet X.X.X.X
	igmpv3 rv 2 qi 125 qri 10 uri 3
		group 224.0.0.1 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX

```

# Link drop (doesn't work)

However, if I power cycle the switch:

```
Dec 3 13:21:43	avahi-daemon	97955	Joining mDNS multicast group on interface igb1.50.IPv6 with address XX::XX.
Dec 3 13:21:43	avahi-daemon	97955	Leaving mDNS multicast group on interface igb1.50.IPv6 with address XX::XX.
Dec 3 13:21:41	avahi-daemon	97955	New relevant interface igb1.50.IPv4 for mDNS.
Dec 3 13:21:41	avahi-daemon	97955	Joining mDNS multicast group on interface igb1.50.IPv4 with address X.X.X.X.
Dec 3 13:21:41	avahi-daemon	97955	Interface igb1.50.IPv4 no longer relevant for mDNS.
Dec 3 13:21:41	avahi-daemon	97955	Leaving mDNS multicast group on interface igb1.50.IPv4 with address X.X.X.X.
Dec 3 13:21:22	avahi-daemon	97955	New relevant interface igb1.50.IPv4 for mDNS.
Dec 3 13:21:22	avahi-daemon	97955	Joining mDNS multicast group on interface igb1.50.IPv4 with address X.X.X.X.
Dec 3 13:21:22	avahi-daemon	97955	Joining mDNS multicast group on interface igb1.50.IPv6 with address XX::XX.
Dec 3 13:21:22	avahi-daemon	97955	IPV6_DROP_MEMBERSHIP failed: Can't assign requested address
Dec 3 13:21:22	avahi-daemon	97955	Leaving mDNS multicast group on interface igb1.50.IPv6 with address fe80::1:1.
Dec 3 13:20:05	avahi-daemon	97955	Joining mDNS multicast group on interface igb1.50.IPv6 with address fe80::1:1.
Dec 3 13:20:05	avahi-daemon	97955	Leaving mDNS multicast group on interface igb1.50.IPv6 with address XX:XX.
Dec 3 13:20:05	avahi-daemon	97955	Interface igb1.50.IPv4 no longer relevant for mDNS.
Dec 3 13:20:05	avahi-daemon	97955	Leaving mDNS multicast group on interface igb1.50.IPv4 with address X.X.X.X.
```

Which is interesting! So it ends up with VLAN 50 in the multicast group...but only VLAN 50. There are no log lines about the other interfaces, and we can see they never join the multicast group:

```
igb1.50:
	inet X.X.X.X
	igmpv3 rv 2 qi 125 qri 10 uri 3
		group 224.0.0.251 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
		group 224.0.0.1 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
igb1.30:
	inet X.X.X.X
	igmpv3 rv 2 qi 125 qri 10 uri 3
		group 224.0.0.1 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
igb1.40:
	inet X.X.X.X
	igmpv3 rv 2 qi 125 qri 10 uri 3
		group 224.0.0.1 mode exclude
			mcast-macaddr XX:XX:XX:XX:XX:XX
```

And I can't bonjour across my VLANs anymore. :)

I would expect whatever trigger avahi to demote igb1.50.IPv4 from relevance and leave the multicast group would also do the same for the other configured VLANs, as well as the subsequent relevance promotion and group join? Or am I thinking about this all wrong?

**Comment by pemensik** [comment]
Interesting. Perhaps avahi needs to track master interface of vlan interfaces. Does this behaviour depend on kernel version? Can you show what uname -a reports on that system?

**Comment by c6rbon** [comment]
Good question!

FreeBSD pfSense 12.3-STABLE FreeBSD 12.3-STABLE RELENG_2_6_0-n226742-1285d6d205f pfSense  amd64

**Comment by evverx** [comment]
To judge from
> IPV6_DROP_MEMBERSHIP failed: Can't assign requested address

avahi failed to leave the multicast group at some point so my guess would be that it's either a firmware/driver/kernel bug preventing avahi from leaving/joining multicast groups or avahi fails to keep track of interfaces for whatever reason. The error messages comes from the code getting around driver bugs so I'm inclined to say it's the former but I'm not 100% sure of course. It should probably be possible to figure out what it is by trying to run any other code that is supposed to leave/join multicast groups. If it can survive that it's an avahi bug. @c6rbon I wonder if you tried reporting it to the pfSense folks? I think they can help to debug this.

**Comment by evverx** [comment]
I think it can be closed. It should probably be reported to pfSense to track it down there properly.

**Comment by c6rbon** [comment]
evverx - apologies! I completely missed your comment from Dec 17, 2023.

I haven't observed this problem in a long time, so I suspect it was exactly as you speculated, and a firmware/driver/kernel fix in pfsense took care of it.  

If it comes up again, I'll try the pfSense folks. Thanks!

**Comment by evverx** [comment]
> I haven't observed this problem in a long time

It's good to know. Thanks! There was a similar issue on FreeBSD where avahi seemingly failed to keep track of interfaces and at the time it was got around there by adding a hook restarting avahi. Hopefully it was the same issue and that kludge is no longer necessary there. (It's hard to tell though because it wasn't possible to track it down either).
