### ISSUE TITLE
nss-mdns service lookup using service: getent services service-discovery-name

### ISSUE THREAD

**Issue by dgtlrift** [avahi/avahi#470]
Add support for services to be searched via name service switch configuration for the services database in addition to the hosts.

```
hosts:          files mdns4_minimal [NOTFOUND=return] dns 
services:       files mdns4_minimal [NOTFOUND=return] 

```
then something like 

`getent services http/tcp`

would translate to a service record lookup for `_http._tcp`

**Comment by evverx** [comment]
>  translate to a service record lookup for _http._tcp

I'm sorry but I'm not sure what it would like and what the use case is. Services are resolved by getting PTR RRs and then getting their SRV and TXT RRs. Key/value pairs from TXT RRs can't be used here, fields other than port from SRV RRs can't be used either. The list of services in general is never complete. `getservbyport` would require scanning all SRV RRs to find ports that match.

I'll go ahead and close this issue but if you can expand on use cases and what it would look like I can always reopen it.
