### ISSUE TITLE
oss-fuzz support should use optional dependencies

### ISSUE THREAD

**Issue by pemensik** [avahi/avahi#473]
Related to PR #459. I think configure part should not require 4 lines of features disabling at ``fuzz/oss-fuzz.sh``.

Instead only core features should be mandatory and have to disable. Other features not strictly necessary to build useful avahi should be optional and just disable themselves unless explicitly requested.

Great example for that is: ``--disable-qt3 --disable-qt4 --disable-qt5 --disable-gtk --disable-gtk3 ``. I think those are bindings for GUI applications. While we want them working, I do not think they should be needed for basic build. Language bindings should be extra, just avahi-daemon should be build-able without rich dependencies.

I think we should support something like [tor oss-fuzz example](https://github.com/google/oss-fuzz/blob/2d5e2ef84f281e6ab789055aa735606d3122fda9/projects/tor/build.sh#L40) has. `` --enable-oss-fuzz `` should be almost everything fuzzing would need. Other things should be made inside configure.ac.

**Comment by evverx** [comment]
As discussed in https://github.com/avahi/avahi/pull/459#issuecomment-1711497247 the build environment should be strictly controlled and in its current form the `--disable-*` flags are much more suitable for that. Other than that as discussed in https://github.com/avahi/avahi/pull/513#issuecomment-1817497932 people packaging stuff generally prefer explicit disable flags.

> --enable-oss-fuzz should be almost everything fuzzing would need

The `enable-oss-fuzz` switch does much more than just enabling/disabling dependencies there so it isn't comparable.

> Other things should be made inside configure.ac

I think ideally avahi should swith to `meson` (or whatever) where `--auto-features=disabled` or something like that can be used.

I think the issue can be closed.
