### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ThomasVolkert** [avahi/avahi#49]
I am wondering if it is possible to compile avahi for Windows environments? (mingw/msys/cygwin or even MSVC?)

Best regards,
Thomas.

**Comment by lathiat** [comment]
The main issue for Windows support (which does not currently exist) is implementing the network handling routines for enumerating interfaces & ip addresses and keeping track of them as they come and go.

See:
https://github.com/lathiat/avahi/blob/master/avahi-core/iface-pfroute.c
https://github.com/lathiat/avahi/blob/master/avahi-core/iface-none.c
https://github.com/lathiat/avahi/blob/master/avahi-core/iface-linux.c

The other more minor issue would be that D-BUS is not really well used on Windows and some other API method would likely be best, though, I believe you can actually compile D-BUS.

**Comment by evverx** [comment]
I think it can be closed. Starting with Windows 10 1703 Microsoft has included native support for multicast DNS so it's what should probably be used there.
