### ISSUE TITLE
After upgrading to iOS17 Password required for “(null)”

### ISSUE THREAD

**Issue by KaElectro** [avahi/avahi#544]
Hello,
I'm using Ubuntu servers with Cups Server installed.
The print job is queried with authentication.
The authentication on the iPad and iPhone also works, the print job is released and printed.
After upgrading from Apple iOS16 to iOS17, I have a big problem with CUPS.
Previously, the access data was saved in the Apple device, so that the next print job did not require re-entering the access data.
The login window says:
Password required for “(null)”
As I said, the print job is executed correctly, but the access data is not saved.
I have it with versions from CUPS 1.7.5 to CUPS 2.4.6 and various Ubuntu versions. Always the same error.
I tested it with Ubuntu Server, Arch Linux, Debian, shows the same issue
Can someone help me.
Any help is appreciated.
Greetings

**Comment by pemensik** [comment]
I do not posses iPhone to test it myself. Do you think you would be able to record exchange on mdns (5353) port? ``tcpdump -nw mdns.pcap port mdns`` command should record mdns exchange.

I just expect they expect some kind of user friendly description. It may depend on what the printer exports. ``avahi-browse -at`` should help you find the printer. ``avahi-browse -rt <type>`` would include more details for given type. That might reveal what printer exports and what might be missing in it.

**Comment by pemensik** [comment]
For a printer types should be ``_ipp.tcp`` or ``ipps.tcp``, for specific printers there might be others.

**Comment by KaElectro** [comment]
Before Apple released the update to iOS17, the printer and server were displayed when the password was asked and were saved in the keychain.
![IMG_2758](https://github.com/avahi/avahi/assets/155311807/f4df21fe-b765-40b1-850e-1ff9280d53c1)
After the update, the printer and server are no longer displayed and saving user data no longer works.
![Passwort](https://github.com/avahi/avahi/assets/155311807/838876ce-d0fe-48f4-b47c-74b518d64372)
the tcpdump:
[mdns.pcap.zip](https://github.com/avahi/avahi/files/13828781/mdns.pcap.zip)
please rename only the file.
Some screenshots from Bonjour Browser:
<img width="394" alt="Bildschirmfoto 2024-01-04 um 11 18 08" src="https://github.com/avahi/avahi/assets/155311807/4f26958e-892c-48fb-ac6b-b176efcd8915">
<img width="347" alt="Bildschirmfoto 2024-01-04 um 11 18 21" src="https://github.com/avahi/avahi/assets/155311807/8343cc1a-e940-47ce-9a2e-132cb0e1fff3">
<img width="347" alt="Bildschirmfoto 2024-01-04 um 11 18 21" src="https://github.com/avahi/avahi/assets/155311807/8df433bc-926a-4866-8afc-f98eea712e28">

Thank you for taking on the problem

**Comment by KaElectro** [comment]
<img width="427" alt="Bildschirmfoto 2024-01-04 um 11 18 39" src="https://github.com/avahi/avahi/assets/155311807/35f9b73c-4321-4e3f-8832-7e9ed5afe5f3">

**Comment by pemensik** [comment]
Oops, interesting. Apple has chosen to query for HTTPS records also on *mdns*. It sends query for both HTTPS and AAAA records, that is certainly unexpected and Avahi does not react to it in any way.

But I think we would need service registration recorded in the traffic. To record that, it would need probably power off and power on the printer. There are no SRV queries or responses for any of required types. Only ``_hap._tcp.local`` response is recorded, but that is not interesting for us.

Also all queries iOS device makes might help. Disconnecting from the network and reconnecting when capturing mdns might help to reveal what it has tried. But primary issue seems to be on iOS interpretation. The device clearly has name assigned and advertised. I am afraid that seems to be issue for iOS to evaluate.

That device iMac, does printing work correctly on it? Also with saving credentials for it? Differences visible from ``avahi-browse -tr _ipp._tcp`` between the test device and iMac might reveal some significant difference.

**Comment by KaElectro** [comment]
The file is from a complete printing process with authentication.
[mdns1.pcap.zip](https://github.com/avahi/avahi/files/13850106/mdns1.pcap.zip)
only rename this file.

I use MacOS Ventura 13.6.3, so printing including saving the access data is no problem. Unfortunately, I don't have a current version available at the moment.

What data is still needed to continue the analysis?

**Comment by evverx** [comment]
I think it can be closed.

Looking at https://github.com/OpenPrinting/cups/issues/863 @KaElectro I wonder if you have you tried reporting it to Apple?
