### ISSUE TITLE
avahi-daemon uses 5-8% of CPU on idle

### ISSUE THREAD

**Issue by Doomsdayrs** [avahi/avahi#557]
The `avahi-daemon` is stuck constantly running and using a significant amount of CPU when the system is idle. This leads to significant battery drain on my laptop.

Why is it using so much CPU time?

---

OS: Fedora 39
Daemon Version: 0.8

**Comment by evverx** [comment]
It's a duplicate of https://github.com/avahi/avahi/issues/210 and was probably fixed in https://github.com/avahi/avahi/pull/366. It would be great if you could apply that patch to see if it helps.

**Comment by Doomsdayrs** [comment]
Thank you for the prompt reply, I will continue this on #366
