### ISSUE TITLE
Release v0.8.1 with critical bugfixes

### ISSUE THREAD

**Issue by Doomsdayrs** [avahi/avahi#558]
0.8.0 was released 4 years ago.

I would like 0.8.1 to be released with the bug fixes for the below critical issue.

https://github.com/avahi/avahi/issues/210
https://github.com/avahi/avahi/pull/366

I am not fully versed in the status of this project.
But I am sure that there are other bug fixes in the last 4 years that can be released to distributions.

**Comment by Doomsdayrs** [comment]
Closing in favor of https://github.com/avahi/avahi/issues/503

**Comment by tiaopao** [comment]
How to download  0.8.1

**Comment by tiaopao** [comment]
@Doomsdayrs 
Would you please tell us how to download 0.8.1

**Comment by evverx** [comment]
There is no 0.8.1. The latest tag is https://github.com/avahi/avahi/releases/tag/v0.9-rc2

**Comment by tiaopao** [comment]
@evverx Thanks a lot!
