### ISSUE TITLE
avahi-daemon responds to A queries on 127.0.0.1 but not ::1

### ISSUE THREAD

**Issue by hhartzer** [avahi/avahi#573]
I've tested this on Debian and FreeBSD with the same result.

Let's say our hostname is "machine".

```
$ drill -Q -p 5353 machine.local a @127.0.0.1
127.0.0.1
$ drill -Q -p 5353 machine.local aaaa @127.0.0.1
::1
```

```
$ drill -Q -p 5353 machine.local aaaa @::1
::1
$ drill -Q -p 5353 machine.local a @::1
Error: error sending query: Could not send or receive, because of network error
```

Not sure if this is intentional or not, but it seems interesting.

**Comment by evverx** [comment]
That's probably because of `publish-aaaa-on-ipv4=yes` and `publish-a-on-ipv6=no`.

Could you set `publish-a-on-ipv6` to `yes` in `/etc/avahi/avahi-daemon.conf`, restart avahi-daemon and try again?

**Comment by hhartzer** [comment]
That worked, thank you!

This must just be the default configuration. I didn't have any such values overridden.

I'll close this out for now.

**Comment by evverx** [comment]
Turns out with the master branch of avahi `dig @::1` doesn't work. I've just opened https://github.com/avahi/avahi/issues/574.

**Comment by hhartzer** [comment]
Ha, nice catch! Seems like it could be something relatively simple to add a test for.

**Comment by evverx** [comment]
I added a test covering `127.0.0.1`, `224.0.0.1` and `ff02::fb` in https://github.com/avahi/avahi/commit/5094350f90110ac46706c2a9b7aba660b4864df9 to prevent regressions at least. That part wasn't covered at all.

The testing infrastructure was more or less set up relatively recently and it would be great to add more tests. https://coveralls.io/builds/65964485 shows that the tests certainly can be improved.
