### ISSUE TITLE
Integrate avahi with Weblate

### ISSUE THREAD

**Issue by evverx** [avahi/avahi#603]
It should make it easier to translate things and pull them automatically without having to open PRs manually. PRs look like https://github.com/systemd/systemd/pull/32828

**Comment by filmsi** [comment]
I really do not know how to open PR ...

**Comment by evverx** [comment]
@filmsi it should be possible to go to https://github.com/avahi/avahi/blob/master/po/sl.po and then follow https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository to replace the file with the updated version and then open a PR via the GitHub user interface.

**Comment by evverx** [comment]
@filmsi it would be great if you could open a PR but I can do that too. Looking at https://github.com/systemd/systemd/commit/be2ad93af3b6af6a939cf347754f5cc50ed1ac17 I think I can attribute the PR properly. Though I'm not sure what should be included in the commit message. To judge from https://l10n.gnome.org/vertimus/484/454/117/ I'm guessing the Slovenian GNOME l10n team should be mentioned too. Just let me know what the commit message should look like.

**Comment by evverx** [comment]
FWIW I've just opened https://pagure.io/fedora-l10n/tickets/issue/40.

**Comment by evverx** [comment]
@filmsi avahi was integrated into Weblate. Could you try https://translate.fedoraproject.org/projects/avahi/master to see if it works?

**Comment by evverx** [comment]
To judge from https://github.com/avahi/avahi/pull/625 it seems to be working. I'll go ahead and close this issue.
