### ISSUE TITLE
ServiceResolver starts enumerating before signals are connected

### ISSUE THREAD

**Issue by ceggers-arri** [avahi/avahi#619]
From the `NEWS` file:
```
API Changes: The avahi-core API and D-Bus API have implemented a new API where
a call to the "New" method can now be split into a "Prepare" and then "Start"
method for some objects.
...
This is because the D-Bus implementation in some languages would only bind to
signals of an object after it was created and had received the new object's
path. This led to such languages missing the initial results sent between the
time the object was created and it had setup a filter to receive it's signals.
```
I use a custom binding (C++/glibmm) for accessing the `avahi-daemon` from my application via D-Bus. In my implementation I bind to signals after object creation and have problems with loosing initial signals although I use the `org.freedesktop.Avahi.Server2` interface for creating the `ServiceResolver`:

```
# The ServiceBrowser has found a new service ...
signal time=1722349804.723254 sender=:1.5 -> destination=:1.1 serial=18 path=/Client0/ServiceBrowser1; interface=org.freedesktop.Avahi.ServiceBrowser; member=ItemNew
   int32 7
   int32 1
   string "MyService"
   string "_arri-lios._tcp"
   string "local"
   uint32 4

# ... so lets create a ServiceResolver for getting the details ...
method call time=1722349804.751823 sender=:1.1 -> destination=org.freedesktop.Avahi serial=53 path=/; interface=org.freedesktop.Avahi.Server2; member=ServiceResolverPrepare
   int32 7
   int32 1
   string "MyService"
   string "_MyServiceSubType._tcp"
   string "local"
   int32 1
   uint32 0

# ... created (but should not send results yet) ...
method return time=1722349804.758707 sender=:1.5 -> destination=:1.1 serial=21 reply_serial=53
   object path "/Client0/ServiceResolver3"

# Uups, the first signal is raised immediately (before it has been registered)
signal time=1722349804.772314 sender=:1.5 -> destination=:1.1 serial=22 path=/Client0/ServiceResolver3; interface=org.freedesktop.Avahi.ServiceResolver; member=Found
   int32 7
   int32 1
   string "MyService"
   string "_MyServiceSubType._tcp"
   string "local"
   string "MyHostName.local"
   int32 1
   string "fe80::1234:1234:1234:1234"
   uint16 80
   array [
      array of bytes "MyTxtData"
   ]
   uint32 5

# signal registration (org.freedesktop.Avahi.ServiceResolver.Found)
method call time=1722349804.781092 sender=:1.1 -> destination=org.freedesktop.DBus serial=54 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.Avahi',interface='org.freedesktop.Avahi.ServiceResolver',member='Found',path='/Client0/ServiceResolver3'"
method return time=1722349804.783647 sender=org.freedesktop.DBus -> destination=:1.1 serial=31 reply_serial=54

# signal registration (org.freedesktop.Avahi.ServiceResolver.Failure)
method call time=1722349804.788678 sender=:1.1 -> destination=org.freedesktop.DBus serial=55 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.Avahi',interface='org.freedesktop.Avahi.ServiceResolver',member='Failure',path='/Client0/ServiceResolver3'"
method return time=1722349804.790565 sender=org.freedesktop.DBus -> destination=:1.1 serial=32 reply_serial=55

# Here I would like to "start" the ServiceResolver
method call time=1722349804.794402 sender=:1.1 -> destination=org.freedesktop.Avahi serial=56 path=/Client0/ServiceResolver3; interface=org.freedesktop.Avahi.ServiceResolver; member=Start
method return time=1722349804.797475 sender=:1.5 -> destination=:1.1 serial=23 reply_serial=56

# No further signals sent, so my application never gets the data for MyService.
```

All this happens directly at startup of my (embedded) system. So it is likely that the service's records are received by `avahi-daemon` just when creating the `ServiceResolver`.

**Comment by evverx** [comment]
Could it be that it was fixed in https://github.com/avahi/avahi/pull/468?

**Comment by evverx** [comment]
I think it's a duplicate of https://github.com/avahi/avahi/issues/446.

**Comment by ceggers-arri** [comment]
> Could it be that it was fixed in #468?

It looks so (I still use v0.8). 

Although I checked in advance for existing issues, I unfortunately didn't find it.

I'll cherry pick #468 into my branch and report the test results tomorrow.

Thank you very much!

**Comment by evverx** [comment]
> I'll cherry pick https://github.com/avahi/avahi/pull/468 into my branch and report the test results tomorrow

I'll keep the issue open until it's confirmed that it's gone then.

As far as I can see that PR was merged with no tests so if you have some code that could be added to the regression testsuite it would be great if you could open a PR.

**Comment by ceggers-arri** [comment]
> I'll keep the issue open until it's confirmed that it's gone then.
It's gone! This issue can be closed.

> As far as I can see that PR was merged with no tests so if you have some code that could be added to the regression testsuite it would be great if you could open a PR.

I haven't worked with the testsuite yet. If you can give me some hints, I'll have a look on it.

**Comment by evverx** [comment]
> It's gone! This issue can be closed.

Got it. Closing.

> I haven't worked with the testsuite yet. If you can give me some hints, I'll have a look on it.

In its current form the testsuite sets up its environment in https://github.com/avahi/avahi/blob/master/.github/workflows/build.sh by installing the build dependencies, compiling avahi with clang/gcc, ASan/UBsan and things like that. Then it runs https://github.com/avahi/avahi/blob/master/.github/workflows/smoke-tests.sh where avahi-daemon and various tests are run. The tests talking to avahi-daemon via D-Bus are in https://github.com/avahi/avahi/blob/master/avahi-client/client-test.c but since in this case `avahi-client` isn't involved maybe it should go to a separate test.

In its current form it isn't obvious how to cover those codepaths unfortunately. I added the "needs-test" label to https://github.com/avahi/avahi/pull/468 as a reminder.
