### ISSUE TITLE
Cross compile error about QT

### ISSUE THREAD

**Issue by jho4255** [avahi/avahi#622]
**Avahi version**
Latest
**Distribution**

**Describe the bug**
Couldn't compile Qt without -fPIC nor with -fPIC

**To Reproduce**
./configure --target=arm-linux-gnueabi --host=arm-linux-gnueabi     CC=/home/hunoh/envs/sysroots/x86_64-starfishsdk-linux/usr/bin/arm-starfishmllib32-linux-gnueabi/arm-starfishmllib32-linux-gnueabi-gcc     STRIP=/home/hunoh/envs/sysroots/ca9v1-starfishmllib32-linux-gnueabi/bin/arm-linux-gnueabi-strip     LDFLAGS="$LDFLAGS --sysroot=/home/hunoh/envs/sysroots/ca9v1-starfishmllib32-linux-gnueabi -L/home/hunoh/envs/sysroots/ca9v1-starfishmllib32-linux-gnueabi/lib -L/home/hunoh/envs/sysroots/ca9v1-starfishmllib32-linux-gnueabi/usr/lib -L/home/hunoh/envs/sysroots/ca9v1-starfishmllib32-linux-gnueabi/usr/lib/arm-starfishmllib32-linux-gnueabi/11.3.0"     CFLAGS="$CFLAGS --sysroot=/home/hunoh/envs/sysroots/ca9v1-starfishmllib32-linux-gnueabi -I/home/hunoh/envs/boost_1_85_0/ -I/home/hunoh/envs/sysroots/ca9v1-starfishmllib32-linux-gnueabi/usr/include/ -fPIC"     CXXFLAGS="$CXXFLAGS --sysroot=/home/hunoh/envs/sysroots/ca9v1-starfishmllib32-linux-gnueabi -I/home/hunoh/envs/boost_1_85_0/ -I/home/hunoh/envs/sysroots/ca9v1-starfishmllib32-linux-gnueabi/usr/include/ -fPIC"     LD=/home/hunoh/envs/sysroots/x86_64-starfishsdk-linux/usr/bin/arm-starfishmllib32-linux-gnueabi/arm-starfishmllib32-linux-gnueabi-ld     --with-distro=none

**Comment by evverx** [comment]
Could you paste `config.log`?

> Avahi version
Latest

Is it reproducible with the master branch?

> Distribution

Could you expand on where that command is run?

**Comment by simmon-nplob** [comment]
It doesn't seem to be a locale issue, and I think I gave too many options. There is no major problem compiling without -fPIC, also manual compilation requires multiple development environments to be installed.

        test environment  F40 / avahi-0.8.tar.gz

**Comment by AhmTaher** [comment]
268906

**Comment by evverx** [comment]
Closing because of lack of response. If you could provide more details as mentioned in https://github.com/avahi/avahi/issues/622#issuecomment-2262602307 it can always be reopened.
