### ISSUE TITLE
About locale setting

### ISSUE THREAD

**Issue by jho4255** [avahi/avahi#623]
I think I should update configure.ac according to log.
![image](https://github.com/user-attachments/assets/c93acfef-cb92-458f-b467-57e310dee3a6)

But because of my locale setting, 'autoupdate' does not work.
![image](https://github.com/user-attachments/assets/eb4e159b-f80c-400a-b602-230fc5012422)

**Comment by evverx** [comment]
Could you fill out the issue template https://github.com/avahi/avahi/blob/master/.github/ISSUE_TEMPLATE/bug_report.md I'm not sure what this issue is about. Could you also update https://github.com/avahi/avahi/issues/622? I'm not sure what that issue is about either.

**Comment by simmon-nplob** [comment]
@jho4255 I think that avahi was intergrated into weblate, and add translation complete. It shoud be resolved!  I will check the relevant parts carefully.

**Comment by evverx** [comment]
Closing because of lack of response. If you could provide more details as mentioned in https://github.com/avahi/avahi/issues/623#issuecomment-2264813420 it can always be reopened.
