### ISSUE TITLE
published wrong ip address

### ISSUE THREAD

**Issue by colttt** [avahi/avahi#643]
**Avahi version**
 avahi-daemon                    0.8-10
**Distribution**
Debian 12  Bookworm
**Describe the bug**
I've a printserver (cups) running, an we have different   Network interfaces (eduroam, guest wifi, etc) but it looks like that avahi always return the IP from the first interface instead of the ip where it receive the query. So when I'm in the network 172.18.0.x Network (ens256) and want to print, printp.local resolves to 172.29.0.5 instead of 172.18.0.5. 
How can I avoid or fix that? In this situation printing is nearly not possible if you're in the 172.18.0.x Network

```
2: ens161: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8c:36:2b brd ff:ff:ff:ff:ff:ff
    altname enp4s0
    inet 172.29.0.5/16 brd 172.29.255.255 scope global ens161
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe8c:362b/64 scope link 
       valid_lft forever preferred_lft forever
3: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8c:28:d9 brd ff:ff:ff:ff:ff:ff
    altname enp11s0
    inet 172.16.101.65/16 brd 172.16.255.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe8c:28d9/64 scope link 
       valid_lft forever preferred_lft forever
4: ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8c:2b:ab brd ff:ff:ff:ff:ff:ff
    altname enp19s0
    inet 172.25.1.4/24 brd 172.25.1.255 scope global ens224
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe8c:2bab/64 scope link 
       valid_lft forever preferred_lft forever
5: ens256: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8c:07:d1 brd ff:ff:ff:ff:ff:ff
    altname enp27s0
    inet 172.18.0.5/16 brd 172.18.255.255 scope global ens256
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe8c:7d1/64 scope link 
       valid_lft forever preferred_lft forever
```

**To Reproduce**
Install cups and avahi, add some printer, add  at least 2 network interfaces with complete different networks, join the network which is not the first interface and try to print

**Expected behavior**
when I got a query to an IP address, answer just from that with that ip address

**Avahi config files if applicable**
(`/etc/avahi/avahi-daemon.conf`, `/etc/avahi/hosts`, `/etc/avahi/services/*.service`)
```
[server]
use-ipv4=yes
use-ipv6=no
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=yes

[publish]
publish-hinfo=no
publish-workstation=no

[reflector]

[rlimits]
```

**Comment by evverx** [comment]
Could you collect mDNS packets sent/received via the ens256 interface when `printp.local` is resolved to see whether the queries/responses go via that interface and what those responses look like?

**Comment by evverx** [comment]
Closing because of lack of response.
