### ISSUE TITLE
Unset DATADIRNAME causing looking at wrong path for locales

### ISSUE THREAD

**Issue by rffontenelle** [avahi/avahi#644]
https://github.com/avahi/avahi/blob/363aaf472687560ba8e9de1aeb6aabcfa133836a/configure.ac#L423

This requires $DATADIRNAME to be passed when being packaged by downstream, but the result is an unset variable causing attempt to find locales at e.g. "/usr//locale/pt_BR/..." and, as a consequence, locales are not being used.

It seems that `common/gettext.m4`, available in the source code after `./autogen.sh`, doesn't set $DATADIRNAME anymore since gettext v0.20 (from 6 years ago). More specifically, after the commit "[Simplify Autoconf macros.](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blobdiff;f=gettext-runtime/m4/gettext.m4;h=2bb12f3b130ec7a4c733f2bdf2b8bea420600822;hp=a91c4dab5b7077dcaa389f40a294c875f89303c0;hb=ed4cb97d6336f193f1aabe479f916469c26611e8;hpb=9c2f617b64314dfd8f338476a4b3f05cee6bb528)".

How about using the same value as datarootdir below?

```
$ ./configure --help
...
  --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
```

**Comment by evverx** [comment]
Thank you for opening the issue! I should have opened it here once I ran into https://pagure.io/fedora-l10n/tickets/issue/40#comment-924641 but didn't get around to it.

> How about using the same value as datarootdir below?

I think it should be `localedir` because it's where all the locales are installed. Though I haven't figured out why `avahilocaledir` is needed and why `GNOMELOCALEDIR` pointing to `$(datadir)/locale` exists as well. In theory it should be possible to replace them all with `localedir`.

**Comment by evverx** [comment]
The following patch seems to fix the issue
```diff
diff --git a/avahi-common/Makefile.am b/avahi-common/Makefile.am
index 11404ce..c0a7c92 100644
--- a/avahi-common/Makefile.am
+++ b/avahi-common/Makefile.am
@@ -77,7 +77,7 @@ libavahi_common_la_SOURCES = \
        utf8.c utf8.h \
        i18n.c i18n.h
 
-libavahi_common_la_CFLAGS = $(AM_CFLAGS) $(PTHREAD_CFLAGS) -DAVAHI_LOCALEDIR=\"$(avahilocaledir)\"
+libavahi_common_la_CFLAGS = $(AM_CFLAGS) $(PTHREAD_CFLAGS) -DAVAHI_LOCALEDIR=\"$(localedir)\"
 libavahi_common_la_LIBADD = $(AM_LDADD) $(PTHREAD_CFLAGS) $(PTHREAD_LIBS) $(INTLLIBS)
 libavahi_common_la_LDFLAGS = $(AM_LDFLAGS)  -version-info $(LIBAVAHI_COMMON_VERSION_INFO)
 
diff --git a/configure.ac b/configure.ac
index 2f63730..a3211b8 100644
--- a/configure.ac
+++ b/configure.ac
@@ -420,9 +420,6 @@ AC_DEFINE_UNQUOTED([GETTEXT_PACKAGE],["$GETTEXT_PACKAGE"],[Gettext package])
 AM_GNU_GETTEXT_VERSION([0.19.8])
 AM_GNU_GETTEXT([external])
 
-avahilocaledir='${prefix}/${DATADIRNAME}/locale'
-AC_SUBST(avahilocaledir)
-
 # Check for pkg-config manually first, as if its not installed the
 # PKG_PROG_PKG_CONFIG macro won't be defined.
 AC_CHECK_PROG(have_pkg_config, pkg-config, yes, no)
```
but I'm still not sure where `avahilocaledir` came from and how safe it is to just drop it. `GNOMELOCALEDIR` should probably point to `localedir` as well.

**Comment by rffontenelle** [comment]
> The following patch seems to fix the issue

I confirm. Tested rebuilding Arch Linux's avahi package and it worked fine.

> but I'm still not sure where `avahilocaledir` came from and how safe it is to just drop it.

Well, it came from the initial i18n support as per https://github.com/avahi/avahi/commit/bb8bd5490a71bc77570653cf53be88edd37679e3

> `GNOMELOCALEDIR` should probably point to localedir as well.

You are talking about [avahi-ui/Makefile.am](https://github.com/avahi/avahi/blob/363aaf472687560ba8e9de1aeb6aabcfa133836a/avahi-ui/Makefile.am#L33), right? Yeah, well, I don't see a reason for not using same value (from `$(localedir)`, in the case)

**Comment by evverx** [comment]
> I confirm. Tested rebuilding Arch Linux's avahi package and it worked fine.

Thanks for testing the patch!

> Well, it came from the initial i18n support as per https://github.com/avahi/avahi/commit/bb8bd5490a71bc77570653cf53be88edd37679e3

Given that it was back in 2007 my guess would be that `localedir` wasn't widely available at the time. To judge from https://git.savannah.gnu.org/cgit/autoconf.git/tree/NEWS#n1503 it was introduced in Autoconf 2.59c (2006-04-12). It should be safe to switch it now.

> You are talking about [avahi-ui/Makefile.am](https://github.com/avahi/avahi/blob/363aaf472687560ba8e9de1aeb6aabcfa133836a/avahi-ui/Makefile.am#L33), right?

Yes, I am. I was trying to find all the places related to the locales one way or another and make them consistent.
