### ISSUE TITLE
Add --port Flag to avahi-browse

### ISSUE THREAD

**Issue by joeymalvinni** [avahi/avahi#649]
At my school, the firewall restricts traffic through port 5353 due to security concerns, which doesn't allow me to discover the Raspberry Pi's which are used in our class over the standard port 5353. To circumvent this issue, the mDNS server on the Pi has been set up by a teacher to respond to queries over port 5358. This required him to patch a custom version of avahi with port 5358 hard-coded in `avahi-core/socket.h`. 

To avoid hard-coding the port, it seems pretty reasonable to me to add a `--port` (`-p`) flag to `avahi-browse`. I am aware of [RFC 6762](https://datatracker.ietf.org/doc/html/rfc6762#appendix-A) and the rationale for the standardization of mDNS querying over port 5353, but I don't see any reason to _not_ have the optional capability to specify a unique port for exceptional cases like this. 

I would be willing to work on this feature if there's interest. Any feedback or thoughts on this would be greatly appreciated!

**Comment by evverx** [comment]
avahi-browse talks to avahi via D-Bus so it would be necessary to add another D-Bus method where ports would be passed and avahi would have to listen on those ports as well (in addition to port 5353) for avahi-browse to work when no port is specified. The logic handling direct unicast queries and legacy queries would have to be adjusted as well. I don't think this sort of complexity should be supported upstream to cover this use case. Sorry.

It should be possible to use, say, drill to send legacy queries to that port.
