### ISSUE TITLE
avahi fails to build on Oracle Solaris with "fdutil.c:63:5: error: implicit declaration of function 'memset' FD_ZERO(&fds);"

### ISSUE THREAD

**Issue by l1gi** [avahi/avahi#663]
**Avahi version**
0.8

**Distribution**
Oracle Solaris

**Describe the bug**
Getting following errors with FD_ZERO() and memset():
```
...
In file included from fdutil.c:24:
fdutil.c: In function 'avahi_wait_for_write':
fdutil.c:63:5: error: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
   63 |     FD_ZERO(&fds);
      |     ^~~~~~~
fdutil.c:30:1: note: include '<string.h>' or provide a declaration of 'memset'
   29 | #include "fdutil.h"
  +++ |+#include <string.h>
   30 | 
...
```
Adding `sys/select.h` and `string.h` headers resolves the issue.

**To Reproduce**
Build on Solaris using gcc14.

**Expected behavior**
No build errors.

**Recommended fix**
Patch attached.
[fdutil.txt](https://github.com/user-attachments/files/17939027/fdutil.txt)

**Comment by evverx** [comment]
> Adding sys/select.h and string.h headers resolves the issue.

`sys/select.h` was added in a2243229bc2fb20b0c010b3830f79ef2d2383ccd in 2007.

> Patch attached.

That patch adds `<sys/time.h>` and `<string.h>`. Could you expand on why it's needed on Oracle Solaris? avahi seems to build fine everywhere else without that patch.

**Comment by l1gi** [comment]
I have looked in it a bit more and found that the only header needed is a `string.h`. And that's because `FD_ZERO` is defined like
```
#define	FD_ZERO(__p)    (void) memset((__p), 0, sizeof (*(__p)))
```
on Solaris. Linux implementation is a bit more complicated, but doesn't require `memset()`.

And because standard says that only `sys/select.h` is necessary it looks rather as a bug in Solaris headers. Sorry for alert, closing as not a bug.

Regards,
m.
