### ISSUE TITLE
Support user-specified MTU

### ISSUE THREAD

**Issue by martinoneutrino** [avahi/avahi#70]
I would like to request support for a user-configured MTU. In the case of a WLAN mixed with a jumbo-frames configured LAN, Multicast DNS packets that exceed the WLAN MTU are silently dropped.
I would see this as being a simple "mtulimit" setting, which would replace the discovered hardware MTU if the setting is lower. This would allow the multicast packets to be sent with the correct maximum size.

**Comment by lathiat** [comment]
What MTU sizes do you have set on your WLAN and LAN, and what packet sizes are you seeing avahi generate that are greater?

**Comment by martinoneutrino** [comment]
LAN is 7000 bytes, and WLAN is standard 1500. avahi generated (on the LAN) a packet of 1772 bytes, which was never received by devices on the WLAN.

**Comment by evverx** [comment]
Closing because I think it's a niche feature and there has been no response: https://github.com/avahi/avahi/pull/71#issuecomment-1781284132.

**Comment by pemensik** [comment]
I think what would be needed more is self-detection of bridged networks. If avahi would be aware eth0 and wlan0 interfaces are bridged, it might lower MTU as long as it knew they are interconnected.

But anyway. Avahi should send announcements both over eth0 and wlan0 with MTU obtained from those interfaces. It should be okay to send bigger packet than wlan0 is using. The problem would be if we did not announce the same thing also on wlan0 with correct size, making this announcement lost. Only then hosts on wlan0 might not receive announcement properly.
